# Generated by Django 4.0.5 on 2022-08-07 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='today_money',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_img',
            name='img',
            field=models.ImageField(default='user/default', upload_to='user/'),
        ),
    ]
