# Generated by Django 4.0.5 on 2022-08-07 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auction', '0002_alter_auction_today_money_alter_user_img_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='check_date',
            field=models.BooleanField(default=False),
        ),
    ]
